repos:
  # Python: Ruff/Black
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.6.8
    hooks:
      - id: ruff
        args: [--fix]
      - id: ruff-format
  - repo: https://github.com/psf/black
    rev: 24.8.0
    hooks:
      - id: black

  # Secrets
  - repo: https://github.com/Yelp/detect-secrets
    rev: v1.5.0
    hooks:
      - id: detect-secrets
        args: ["--baseline", ".secrets.baseline"]

  # JS/TS: ESLint / Prettier (local hooks)
  - repo: local
    hooks:
      - id: eslint
        name: eslint
        entry: bash -c 'cd /Users/al02475493/Documents/ai-script-generator-v3 && pnpm lint'
        language: system
        pass_filenames: false
      - id: prettier
        name: prettier
        entry: bash -c 'cd /Users/al02475493/Documents/ai-script-generator-v3 && pnpm format'
        language: system
        pass_filenames: false