# Prometheus configuration for production environment
global:
  scrape_interval: 30s
  evaluation_interval: 30s
  external_labels:
    environment: 'production'
    service: 'generation-service'

rule_files:
  - "/etc/prometheus/rules/*.yml"
  - "/etc/prometheus/rules/generation_service.yml"

scrape_configs:
  # Generation Service metrics (multiple replicas)
  - job_name: 'generation-service'
    static_configs:
      - targets: ['generation-service:8000']
    metrics_path: '/api/monitoring/metrics/prometheus'
    scrape_interval: 30s
    scrape_timeout: 10s
    honor_labels: true

  # Redis metrics
  - job_name: 'redis'
    static_configs:
      - targets: ['redis:6379']
    metrics_path: '/metrics'
    scrape_interval: 30s

  # Nginx metrics (if nginx_exporter is added)
  - job_name: 'nginx'
    static_configs:
      - targets: ['nginx:9113']
    metrics_path: '/metrics'
    scrape_interval: 30s

  # Node exporter for system metrics
  - job_name: 'node'
    static_configs:
      - targets: ['node-exporter:9100']
    scrape_interval: 30s

  # Prometheus self-monitoring
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
    scrape_interval: 30s

alerting:
  alertmanagers:
    - static_configs:
        - targets:
          - alertmanager:9093

# Recording rules for performance optimization (defined above in rule_files section)
